import { Report, Sayembara, Profile } from './supabase';

export const DUMMY_REPORTS: Report[] = [
  // Jakarta
  {
    id: 'rep-001',
    reporter_wallet: '0x123...abc',
    category: 'pothole',
    provinsi_id: 31,
    lat: -6.1751,
    lng: 106.865,
    photo_url: 'https://imgcdn.espos.id/@espos/images/2023/02/jalan-rusak-karanganyar.jpeg?quality=60',
    upvote_count: 12,
    status: 'pending',
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'rep-002',
    reporter_wallet: '0x456...def',
    category: 'crime',
    provinsi_id: 31,
    lat: -6.1755,
    lng: 106.827,
    photo_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWr9h1aCju5BJn4Hnvq15tyIPcP_L2WVRXCw&s',
    upvote_count: 5,
    status: 'confirmed',
    solana_tx: '5xabc123...',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  // Bandung
  {
    id: 'rep-005',
    reporter_wallet: '0xabc...def',
    category: 'pothole',
    provinsi_id: 32,
    lat: -6.9175,
    lng: 107.6191,
    photo_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPj90YIzRkZAxyhD0V0hPiFEodvkdzdgNkDQ&s',
    upvote_count: 15,
    status: 'pending',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  // Surabaya
  {
    id: 'rep-006',
    reporter_wallet: '0xsur...abc',
    category: 'pothole',
    provinsi_id: 35,
    lat: -7.2575,
    lng: 112.7521,
    photo_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPj90YIzRkZAxyhD0V0hPiFEodvkdzdgNkDQ&s',
    upvote_count: 32,
    status: 'confirmed',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  // Medan
  {
    id: 'rep-007',
    reporter_wallet: '0xmed...abc',
    category: 'crime',
    provinsi_id: 12,
    lat: 3.5952,
    lng: 98.6722,
    photo_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWr9h1aCju5BJn4Hnvq15tyIPcP_L2WVRXCw&s',
    upvote_count: 8,
    status: 'pending',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
  },
  // Makassar
  {
    id: 'rep-008',
    reporter_wallet: '0xmak...abc',
    category: 'pothole',
    provinsi_id: 73,
    lat: -5.1477,
    lng: 119.4327,
    photo_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPj90YIzRkZAxyhD0V0hPiFEodvkdzdgNkDQ&s',
    upvote_count: 21,
    status: 'confirmed',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
  // Bali
  {
    id: 'rep-009',
    reporter_wallet: '0xbal...abc',
    category: 'crime',
    provinsi_id: 51,
    lat: -8.4095,
    lng: 115.1889,
    photo_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWr9h1aCju5BJn4Hnvq15tyIPcP_L2WVRXCw&s',
    upvote_count: 45,
    status: 'confirmed',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
  },
];

export const DUMMY_SAYEMBARA: Sayembara[] = [
  {
    id: 'say-001',
    author_wallet: '0xorg...111',
    title: 'Perbaikan Jalan Jakarta Pusat',
    category: 'pothole',
    provinsi_id: 31,
    total_deposit: 10,
    deadline: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7).toISOString(),
    status: 'active',
    confirmed_count: 45,
    reward_per_report: 0.1,
    solana_escrow_pda: 'escrow123...',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  {
    id: 'say-002',
    author_wallet: '0xorg...222',
    title: 'Monitor Keamanan Jakarta Timur',
    category: 'crime',
    provinsi_id: 31,
    total_deposit: 25,
    deadline: new Date(Date.now() + 1000 * 60 * 60 * 24 * 14).toISOString(),
    status: 'active',
    confirmed_count: 12,
    reward_per_report: 0.5,
    solana_escrow_pda: 'escrow456...',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
];

export const DUMMY_PROFILE: Profile = {
  id: 'prof-001',
  wallet: 'vS123...xyz',
  is_verified_org: false,
  reputation: 850,
  created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
};
